name: GraphQL Schema Update

on:
  push:
  workflow_dispatch:
    inputs:
      app_env:
        type: choice
        description: Environment you want to check against
        required: false
        default: stage
        options:
          - stage
          - dev
          - prod

jobs:
  update-graphql-schema:
    name: Update GraphQL Schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/setup-node@v2
        with:
          node-version: "14.17"

      # - run: type > schema.graphql
      # - run: type > test.txt

      # - run: type > src/store/apollo/schema.graphql

      - run: hello > src/store/apollo/possibleTypes/introspectionResults.ts

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/github-script@v6
        env:
          REACT_APP_SERVICES_ENV: ${{ github.event.inputs.app_env }}
        with:
          script: |
            console.log(process.env);
            console.log("i'm being triggered!")

      - name: Create/Update Pull Request for GraphQL SDL
        uses: lucaslim/ed3-web/.github/actions/create-schema-pull-request@lucaslim-patch-16
        with:
          path: "src/store/apollo/schema.graphql"
          commit-message: "[hotfix] update schema definition language 🩻"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create/Update Pull Request for Possible Types
        uses: lucaslim/ed3-web/.github/actions/create-schema-pull-request@lucaslim-patch-16
        with:
          path: "src/store/apollo/possibleTypes/introspectionResults.ts"
          commit-message: "[hotfix] update possible types 🔮"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create/Update Pull Request for GraphQL Schema & Operation types
        uses: lucaslim/ed3-web/.github/actions/create-schema-pull-request@lucaslim-patch-16
        with:
          path: "src/store/api/graph/interfaces/types.ts"
          commit-message: "[hotfix] update graphql schema/operation types ⛓"
          token: ${{ secrets.GITHUB_TOKEN }}
