
name: GraphQL Schema Update

on:
  workflow_dispatch:
    inputs:
      app_env:
        type: choice
        description: Environment you want to check against
        required: false
        default: stage
        options:
          - stage
          - dev
          - prod

jobs:
  update-graphql-schema:
    name: Update GraphQL Schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: '14.17'
          
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/github-script@v6
        env:
          REACT_APP_SERVICES_ENV: ${{ github.event.inputs.app_env }}
        with:
          script: |
            console.log(process.env);
            console.log("i'm being triggered!")
            
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          commit-message: '[bot] Update GraphQL Schema'
          committer: GitHub <itsa@me.mar.io>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch:  lucaslim-patch-1
          delete-branch: true
          title: '[bot] Update GraphQL Schema'
          body: |
            - GraphQL schema has been updated

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/lucaslim/ed3-web/pulls          
          labels: automerge # required if using automerge-action
    
    
