name: GraphQL Schema Update

on:
  push:
  workflow_dispatch:
    inputs:
      app_env:
        type: choice
        description: Environment you want to check against
        required: false
        default: stage
        options:
          - stage
          - dev
          - prod

jobs:
  update-graphql-schema:
    name: Update GraphQL Schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: "14.17"

      - run: type > test.txt

      - run: type > src/store/apollo/schema.graphql

      - run: echo "hello world" > src/store/apollo/possibleTypes/introspectionResults.ts

      - run: echo "hello world" > src/store/apollo/possibleTypes/should-not-commit.ts

      - run: echo "hello world2" > src/store/api/graph/interfaces/types.ts

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/github-script@v6
        env:
          REACT_APP_SERVICES_ENV: ${{ github.event.inputs.app_env }}
        with:
          script: |
            console.log(process.env);
            console.log("i'm being triggered!")

      - name: Create Pull Request
        uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "[hotfix] Dev API updates - GraphQL Schema update and Regenerated types ${{ steps.date.outputs.date }} 🚀"
          body: |
            ## GraphQL Schema Update 🚀

            🔎  **Found new changes in [EDealer's](https://github.com/carmigo/edealer-graphql) GraphQL Schema.**

            Please verify before merging. If there are breaking changes to address, create a separate branched PR. Avoid coupling any code changes with the schema updates if possible.
          assignees: lucaslim
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          auto-merge: squash
          branch: "hotfix/schema-update"
          path: "schema.graphql"
          commit-message: "[hotfix] schema.graphql change ${{ steps.date.outputs.date }} 🚀"
          labels: category/internal
          update-pull-request-title-and-body: true

      - name: Create Pull Request
        uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "[hotfix] Dev API updates - GraphQL Schema update and Regenerated types ${{ steps.date.outputs.date }} 🚀"
          body: |
            ## GraphQL Schema Update 🚀

            🔎  **Found new changes in [EDealer's](https://github.com/carmigo/edealer-graphql) GraphQL Schema.**

            Please verify before merging. If there are breaking changes to address, create a separate branched PR. Avoid coupling any code changes with the schema updates if possible.
          assignees: lucaslim
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          auto-merge: squash
          branch: "hotfix/schema-update"
          path: "src/api/schema.graphql"
          commit-message: "[hotfix] src/api/schema.graphql change ${{ steps.date.outputs.date }} 🚀"
          labels: category/internal
          update-pull-request-title-and-body: true
