name: GraphQL Inspector

on:
  push:
  pull_request:
    types: [unlabeled, labeled]

jobs:
  test:
    name: Check Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: "main:schema.graphql"
