name: Jira

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: https://einc.atlassian.net
          JIRA_USER_EMAIL: lucas.lim@eblock.ca
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create
        id: create
        uses: atlassian/gajira-create@master
        with:
          project: ED
          issuetype: Task
          summary: |
            [WEB] Deploy X.X.X to Production
          description: |
            In order to deploy the web app to prod, we follow the process outlined [here|https://einc.atlassian.net/l/cp/mrU42BW5#Staging---stage].

            This process is broken into subtasks to be completed among the squads and deployer.
          fields: >-
            {
              "component": "ED3 Build and Deployment",
              "repository": "edealer-web-v2"
            }

      - name: Log created issue
        run: echo "Issue ${{ steps.create.outputs.issue }} was created"
