name: Jira

on: push

jobs:
  login:
    runs-on: ubuntu-latest
    name: Login
    steps:
      - name: Login
        uses: atlassian/gajira-login@v2.0.1
        env:
          JIRA_BASE_URL: https://einc.atlassian.net
          JIRA_USER_EMAIL: lucas.lim@eblock.ca
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Persist config to workspace
        uses: actions/upload-artifact@v3
        with:
          name: config
          path: |
            ${{ github.workspace }}/.jira.d/*
            ${{ github.workspace }}/jira/*
          retention-days: 1

  create-deployment-task:
    runs-on: ubuntu-latest
    name: Create Deployment Ticket
    needs: [login]
    outputs:
      issueNumber: ${{ steps.create.outputs.issue }}
    steps:
      - name: Restore config
        uses: actions/download-artifact@v3
        with:
          name: config
          path: |
            ${{ github.workspace }}/.jira.d/*
            ${{ github.workspace }}/jira/*

      - name: Create
        id: create
        uses: atlassian/gajira-create@v2.0.1
        with:
          project: ED
          issuetype: Task
          summary: |
            [WEB] Deploy X.X.X to Production
          description: |
            In order to deploy the web app to prod, we follow the process outlined [here|https://einc.atlassian.net/l/cp/mrU42BW5#Staging---stage].

            This process is broken into subtasks to be completed among the squads and deployer.
          fields: >-
            {
              "assignee": { "id": "62e923b550bd9783f62ac424" },
              "components": [{ "name": "ED3 Build and Deployment" }],
              "customfield_10048": [{ "value": "edealer-web-2" }],
              "priority": { "id": "2" }
            }

      - name: Log created issue
        run: echo "Issue ${{ steps.create.outputs.issue }} was created"

  create-deployment-subtask:
    runs-on: ubuntu-latest
    name: Create Deployment Subtasks
    needs: [create-deployment-task]
    strategy:
      matrix:
        users: [
            # Anthony
            { user: "6241d45af813eb00692829f7", squad: "Blue" },
            # Tyler
            { user: "6128fbab0bbbf90071170fc8", squad: "Inventory" },
          ]
    steps:
      - name: Create
        id: create
        uses: atlassian/gajira-create@master
        with:
          project: ED
          issuetype: SubTask
          summary: |
            [WEB] ${{ matrix.squad }} Squad X.X.X release verification
          description: |
            h2. Latest Dev api updates

            * (post PR link for squad dev api updates corresponding to latest stage)
            * Should always regenerate API updates the day new stage is released to ensure no missed updates.

            h2. LD flags on prod env are properly set e.g. for new/partial features etc

            * (what FFs were verified?)

            h2. QA of bugs/features on stage env

            * (summary of what was tested by squad)

            h2. All automated tests pass

            * (post link to cypress run here)



            ----

            h3. Reference:

            [https://einc.atlassian.net/l/cp/5NPANkvr|https://einc.atlassian.net/l/cp/5NPANkvr|smart-link]
          fields: >-
            {
              "assignee": { "id": "${{ matrix.user }}" },
              "components": [{ "name": "ED3 Build and Deployment" }],
              "customfield_10048": [{ "value": "edealer-web-2" }],
              "parent": "${{ needs.create-deployment-task.output.issueNumber }}"
              "priority": { "id": "2" }
            }
