on: [push, workflow_dispatch]

jobs:
  print-thingz:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      env:
        HELLO: WORLD
      with:
        script: |
          console.log(process.env);
          console.log("i'm being triggered!")
