name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      reason:
        description: Reason for manual deployment
        required: true
        type: string
      env:
        description: Environment to deploy to
        required: true
        type: choice
        default: stage
        options:
          - stage
          - prod

env:
  REACT_APP_SERVICES_ENV: ${{ github.event.inputs.env }}

jobs:
  context:
    runs-on: ubuntu-latest
    needs: setup-matrix
    steps:
      - run: echo "${{ github.event.inputs.reason }}"
      - run: echo $REACT_APP_SERVICES_ENV
      - run: echo "${{ needs.setup-matrix.outputs.matrix-combinations }}"

  setup-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Setup matrix combinations
        id: matrix-paths
        run: |
          MATRIX_PATHS='
              {"foo": "foo-1", "bar": "bar-1"},
              {"foo": "foo-1", "bar": "bar-2"},
              {"foo": "foo-2", "bar": "bar-1"},
          '
          echo ::set-output name=matrix-combinations::{\"include\":[$MATRIX_PATHS]}
    outputs:
      matrix-combinations: ${{ steps.matrix-paths.outputs.matrix-combinations }}

  matrix-job:
    runs-on: ubuntu-latest
    needs: setup-matrix
    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix-combinations) }}
    steps:
      - run: |
          echo foo=${{ matrix.foo }}
          echo bar=${{ matrix.bar }}
