name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      reason:
        description: Reason for manual deployment
        required: true
        type: string
      env:
        description: Environment to deploy to
        required: true
        type: choice
        default: stage
        options:
          - stage
          - prod

env:
  REACT_APP_SERVICES_ENV: ${{ github.event.inputs.env }}

jobs:
  prep-matrix:
    runs-on: ubuntu-latest
    needs: [context]
    steps:
      - name: Set Sourcemap Paths
        id: sourcemap-paths
        if: github.event.inputs.env == 'stage'
        run: echo ::set-output name=sourcemap-paths::{\"paths\":["https://stage.getedealer.com"]}
      - name: Set Sourcemap Paths
        id: sourcemap-paths
        if: github.event.inputs.env == 'prod'
        run: echo ::set-output name=sourcemap-paths::{\"paths\":["https://ed3.edealer.ca","https://beta.getedealer.com"]}
    outputs:
      sourcemap-paths: ${{ steps.steps.sourcemap-paths.outputs.sourcemap-paths }}

  upload-sourcemap:
    runs-on: ubuntu-latest
    needs: [prep-matrix]
    if: ${{ always() && needs.stage.result == 'success' || needs.prod.result == 'success' }}
    strategy:
      matrix: ${{ fromJson(needs.steps.sourcemap-paths.outputs.sourcemap-paths) }}
    steps:
      - run: |
          echo foo=${{ matrix.paths }}

  context:
    runs-on: ubuntu-latest
    needs: setup-matrix
    steps:
      - run: echo "${{ github.event.inputs.reason }}"
      - run: echo $REACT_APP_SERVICES_ENV
      - run: echo "${{ needs.setup-matrix.outputs.matrix-paths }}"

  setup-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Setup matrix combinations
        id: matrix-paths
        run: |
          MATRIX_PATHS='
              "https://ed3.edealer.ca",
              "https://beta.getedealer.com"
          '
          echo ::set-output name=matrix-paths::{\"paths\":[$MATRIX_PATHS]}
    outputs:
      matrix-paths: ${{ steps.matrix-paths.outputs.matrix-paths }}

  matrix-job:
    runs-on: ubuntu-latest
    needs: setup-matrix
    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix-paths) }}
    steps:
      - run: |
          echo foo=${{ matrix.paths }}
