name: Check

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  limit-pr-per-author:
    name: Limit number of open PRs by author
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      # must keep this extra checkout step until this bug is fixed: https://github.com/actions/checkout/issues/692
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check PR Limit
        uses: lucaslim/pull-request-limiter-action@main
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          limit: 2
          auto_close: false
          body: yo
