name: Push

on:
  pull_request:
    types:
      - opened
    branches:
      - master
  pull_request_review:
    types:
      - dismissed
    branches:
      - master

jobs:
  github-bot-approve:
    if: startsWith(github.head_ref, 'renovate/')
    runs-on: ubuntu-latest
    steps:
      - uses: lucaslim/renovate-auto-approve-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  edealer-bot-approve:
    if: startsWith(github.head_ref, 'renovate/')
    runs-on: ubuntu-latest
    steps:
      - name: Generate App Token
        uses: tibdex/github-app-token@v1.7.0
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: lucaslim/renovate-auto-approve-action@main
        with:
          token: ${{ steps.generate-token.outputs.token }}
