name: Notify 🔊

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
      includeActor:
        required: false
        type: boolean
        default: false
      thread:
        required: false
        type: string
    outputs:
      ts:
        value: ${{ jobs.slack.outputs.ts }}
      thread_ts:
        value: ${{ jobs.slack.outputs.thread_ts }}

jobs:
  slack:
    name: 💬 Send Message to Slack 🚀
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
    outputs:
      ts: ${{ steps.slack-include-actor.outputs.ts || steps.slack.outputs.ts }}
      thread_ts: ${{ steps.slack-include-actor.outputs.thread_ts || steps.slack.outputs.thread_ts }}
    steps:
      - name: Preparing Slack Message
        id: prepare-slack-message
        run: |
          SLACK_MESSAGE="${{ inputs.message }}"
          SLACK_MESSAGE="$(echo "$SLACK_MESSAGE" | sed -z 's/\n/\\n/g')"
          echo "::set-output name=message::${SLACK_MESSAGE}"

      - name: Slack Notification (include Actor)
        id: slack-include-actor
        if: ${{ inputs.includeActor }}
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id:
            C0461JBK90R
            # ${{ inputs.thread != '' && format('"thread_ts": "{0}",', inputs.thread) || '' }}
          payload: >-
            {
              "thread_ts": "1665758673.234399",
              "icon_url": "https://i.ibb.co/NjrgqSk/EDealer-E.png",
              "attachments": [
                {
                  "color": "good",
                  "author_name": "${{ github.actor }}",
                  "author_link": "https://github.com/${{ github.actor }}",
                  "author_icon": "https://github.com/${{ github.actor }}.png?size=32",
                  "fields": [
                    {
                      "title": "",
                      "short": false,
                      "value": "${{ steps.prepare-slack-message.outputs.message }}"
                    }
                  ]
                }
              ]
            }
      - run: |
          echo ${{ toJSON(steps.slack-include-actor.outputs) }}
          echo ${{ steps.slack-include-actor.outputs.thread_ts }}
          echo ${{ steps.slack-include-actor.outputs.ts }}
        if: ${{ inputs.includeActor }}

      - name: Slack Notification
        id: slack
        if: ${{ !inputs.includeActor }}
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: C0461JBK90R
          payload: >-
            {
              ${{ inputs.thread != '' && format('"thread_ts": "{0}",', inputs.thread) || '' }}
              "icon_url": "https://i.ibb.co/NjrgqSk/EDealer-E.png",
              "text": "${{ steps.prepare-slack-message.outputs.message }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ steps.prepare-slack-message.outputs.message }}"
                  }
                }
              ]
            }

      - run: |
          echo ${{ steps.slack.outputs.thread_ts }}
          echo ${{ steps.slack.outputs.ts }}
        if: ${{ !inputs.includeActor }}
